//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RISWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTable
    {
        public int Id { get; set; }
        public string UrlTitle { get; set; }
        public string Title { get; set; }
        public string Categories { get; set; }
        public string Tags { get; set; }
        public string Html { get; set; }
        public string IsTagged { get; set; }
    }
}
